version: "3.8"
services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../:/app/
    env_file: "../.env"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_auth_dev:/var/lib/postgresql/data

volumes:
  pgdata_auth_dev:
